theme: jekyll-theme-midnight
title: "Devika Dass — Photonic Networks Research Portfolio"
description: "Postdoctoral Researcher | Advanced Optical Networks | Si-PICs | ARoF | Coherent Transmission | 6G Transport"
url: "https://dassd-adaptSuggest.github.io"
baseurl: "/optical-networks-portfolio"
show_downloads: false