theme: jekyll-theme-midnight
title: "Devika Dass — Photonic Networks Research Portfolio"
description: "Postdoctoral Researcher | Advanced Optical Networks | Si-PICs | ARoF | Coherent Transmission | 6G Transport"
url: "https://github.com/dassd-adapt/optical-networks-portfolio"
baseurl: ""
show_downloads: false
